import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { stripe, STRIPE_CONFIG, formatAmountForStripe } from '@/lib/stripe';
import { supabase } from '@/lib/supabase';
import { z } from 'zod';
import { randomUUID } from 'crypto';

const createPaymentIntentSchema = z.object({
  packageType: z.enum(['basic', 'premium', 'ultimate']),
  contestantId: z.string().uuid(),
});\n\nexport async function POST(req: NextRequest) {\n  try {\n    const session = await getServerSession(authOptions);\n    \n    if (!session?.user) {\n      return NextResponse.json(\n        { error: 'Authentication required' },\n        { status: 401 }\n      );\n    }\n\n    const body = await req.json();\n    const { packageType, contestantId } = createPaymentIntentSchema.parse(body);\n\n    // Verify contestant exists and is active\n    const { data: contestant, error: contestantError } = await supabase\n      .from('Contestant')\n      .select('id, firstName, lastName, isActive, isEliminated')\n      .eq('id', contestantId)\n      .single();\n\n    if (contestantError || !contestant) {\n      return NextResponse.json(\n        { error: 'Contestant not found' },\n        { status: 404 }\n      );\n    }\n\n    if (!contestant.isActive || contestant.isEliminated) {\n      return NextResponse.json(\n        { error: 'Contestant is not eligible for voting' },\n        { status: 400 }\n      );\n    }\n\n    const votePackage = STRIPE_CONFIG.votePackages[packageType];\n    const amount = formatAmountForStripe(votePackage.price);\n\n    // Create payment intent\n    const paymentIntent = await stripe.paymentIntents.create({\n      amount,\n      currency: STRIPE_CONFIG.currency,\n      metadata: {\n        userId: session.user.id,\n        contestantId,\n        packageType,\n        voteCount: votePackage.votes.toString(),\n      },\n      description: `${votePackage.votes} votes for ${contestant.firstName} ${contestant.lastName}`,\n    });\n\n    // Store payment record in database\n    const paymentId = randomUUID();\n    const { error: paymentError } = await supabase\n      .from('Payment')\n      .insert({\n        id: paymentId,\n        userId: session.user.id,\n        contestantId,\n        stripePaymentIntentId: paymentIntent.id,\n        amount: votePackage.price,\n        voteCount: votePackage.votes,\n        packageType,\n        status: 'pending',\n        createdAt: new Date().toISOString(),\n        updatedAt: new Date().toISOString(),\n      });\n\n    if (paymentError) {\n      console.error('Error storing payment record:', paymentError);\n      // Continue anyway - we can recover from webhook\n    }\n\n    return NextResponse.json({\n      clientSecret: paymentIntent.client_secret,\n      paymentIntentId: paymentIntent.id,\n      amount: votePackage.price,\n      voteCount: votePackage.votes,\n    });\n  } catch (error) {\n    console.error('Payment intent creation error:', error);\n    return NextResponse.json(\n      { error: 'Failed to create payment intent' },\n      { status: 500 }\n    );\n  }\n}"